package com.github.link2fun.hello.entity.dto;

import com.easy.query.core.annotation.Navigate;
import com.easy.query.core.enums.RelationTypeEnum;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;
import lombok.Getter;

import java.math.BigDecimal;
import java.util.List;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link com.github.link2fun.hello.entity.User }
 * 
 * @author easy-query
 */
@Data
public class UserDTO {

  /** 用户的唯一标识符 */
  private String id;
  /** 用户的姓名 */
  private String name;
  /** 密码 */
  @Getter
  @JsonFormat
  @JsonProperty(value = "hello")
  private String password;
  /** 用户的账户列表 */
  @Navigate(value = RelationTypeEnum.OneToMany)
  private List<InternalAccount> accountList;

  /**
   * {@link com.github.link2fun.hello.entity.UserAccount }
   *
   */
  @Data
  public static class InternalAccount {
    /** 用户账户的唯一标识符 */
    private String id;
    /** 用户的唯一标识符 */
    private String userId;
    /** 平台名称 */
    private String platform;
    /** 用户昵称 */
    private String nickName;
    /** 用户的联合ID */
    private String unionId;
    /** 用户的开放ID */
    private String openId;
    /** 账户余额 */
    private BigDecimal amount;

  }

}
