package com.github.link2fun.system.modular.role.model.req;

import lombok.Data;
import org.noear.solon.validation.annotation.NotNull;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link com.github.link2fun.support.core.domain.entity.SysRole }
 *
 * @author easy-query
 */
@Data
public class SysRoleChangeStatusReq {


  /** 角色ID */
  @NotNull(message = "角色ID不能为空")
  private Long roleId;
  /** 角色状态（0正常 1停用） */
  @NotNull(message = "角色状态不能为空")
  private String status;


}
