package com.github.link2fun.system.modular.config.model.vo;


import com.easy.query.core.annotation.UpdateIgnore;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.ser.std.ToStringSerializer;
import com.github.link2fun.support.annotation.Excel;
import lombok.Data;

import java.time.LocalDateTime;

/**
 * this file automatically generated by easy-query struct dto mapping
 * 当前文件是easy-query自动生成的 结构化dto 映射
 * {@link com.github.link2fun.system.modular.config.model.SysConfig }
 *
 * @author easy-query
 */
@Data
public class SysConfigDetailVO {


  /** 参数主键 */
  @Excel(name = "参数主键", cellType = Excel.ColumnType.NUMERIC)
  @JsonSerialize(using = ToStringSerializer.class)
  private Long configId;
  /** 参数名称 */
  @Excel(name = "参数名称")
  private String configName;
  /** 参数键名 */
  @Excel(name = "参数键名")
  private String configKey;
  /** 参数键值 */
  @Excel(name = "参数键值")
  private String configValue;
  /** 系统内置（Y是 N否） */
  @Excel(name = "系统内置", readConverterExp = "Y=是,N=否")
  private String configType;
  /** 备注 */
  private String remark;
  /** 创建者 */
  @UpdateIgnore
  private String createBy;
  /** 创建时间 */
  @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
  @UpdateIgnore
  private LocalDateTime createTime;
  /** 更新者 */
  private String updateBy;
  /** 更新时间 */
  @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
  private LocalDateTime updateTime;


}
